# Dependencies
markdown:         kramdown
highlighter:      pygments
plugins:
    - jekyll-gist
    - jekyll-paginate

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Yu-Tai Lin
tagline:          ''
description:      ''
url:              http://yutailin1993.github.io
baseurl:          /

author:
  name:           'Yu-Tai Lin'
  url:            

paginate:         5

# Custom vars
# version:          2.1.0

github:
  repo:           https://github.com/yutailin1993
